REQUIRE
src/IntervalArithmetic.jl
src/decorations/intervals.jl
src/intervals/conversion.jl

These were ambiguous on 0.4. They don't seem to be required any more, but see IntervalRootFinding tests.

Remove ForwardDiff dependency

---

src/IntervalArithmetic.jl
src/intervals/rounding.jl

This suppresses the annoying redefinition warnings spewed out by changing the Interval rounding type via `setrounding(Interval, r)`.
It is careful to suppress *only* those warnings; anything else should immediately throw an error.

Suppress redefinition warnings in setrounding(Interval)

---

NEWS.md
REQUIRE
docs/src/usage.md
src/IntervalArithmetic.jl
src/intervals/arithmetic.jl
src/intervals/rounding.jl
src/multidim/intervalbox.jl
test/REQUIRE
test/interval_tests/intervals.jl
test/interval_tests/numeric.jl
test/interval_tests/rounding.jl
test/runtests.jl

Use `FastRounding.jl` as a drop-in replacement for changing the rounding mode. This gives a 3-4x speed-up for basic arithmetic operations.

Use FastRounding for speed

---

src/IntervalArithmetic.jl
src/intervals/special.jl
test/interval_tests/consistency.jl

Add isatomic function and tests

---

src/intervals/arithmetic.jl
src/intervals/special.jl
test/interval_tests/consistency.jl

This change makes multiplication of 2 intervals almost twice as fast! And division 30% faster (24 ns instead of 35).

Speed up multiplication and division

---

benchmark/benchmarks.jl
src/IntervalArithmetic.jl
src/intervals/arithmetic.jl
src/intervals/intervals.jl
src/intervals/macros.jl
src/multidim/intervalbox.jl
test/interval_tests/consistency.jl
test/interval_tests/construction.jl
test/interval_tests/numeric.jl
test/interval_tests/rounding.jl
test/runtests.jl

The `IA_VALID` environment variable now determines if validity checks are used. E.g. run Julia with
```
IA_VALID=true julia --compilecache=no
```
to turn on validity checks; by default, they are off.

Make Interval constructor fast by not including checks

---

docs/src/usage.md

These seem like they were from a long time ago, and so they don't need to be referenced in the current docs. Doing different releases of the docs will handle this more naturally in the future.

No need for version references

---

test/interval_tests/rounding.jl

Following https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/72

catch missing prev_float

---

.travis.yml
src/IntervalArithmetic.jl

It is too annoying not to have `Interval` exported.

Reexport Interval

---

src/intervals/conversion.jl
src/intervals/intervals.jl
src/parsing.jl
test/REQUIRE
test/display_tests/display.jl
test/interval_tests/construction.jl
test/interval_tests/parsing.jl

- Change definition of `..` back to give tight intervals.
- Add `convert(Interval, s::String)`

Revert dotdot

---

src/decorations/intervals.jl
src/intervals/conversion.jl
src/intervals/functions.jl
src/intervals/hyperbolic.jl
src/intervals/intervals.jl
src/intervals/macros.jl
src/intervals/precision.jl
src/intervals/trigonometric.jl
test/interval_tests/construction.jl

This implements https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/104#issuecomment-379126777.
* `closure` essentially does what `convert` did previously.
* `convert` will now avoid calling `closure` when doing so makes sense
* all explicit uses of `convert` in the package are replaced with `closure`
Result:
```julia
julia> x = 0.1..0.2
[0.0999999, 0.200001]
julia> @btime 3.1 + $x
19.124 ns (0 allocations: 0 bytes)
[3.19999, 3.30001]
```
Fixes https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/104.
I'm not married to the name `closure`, but it kind of works.
~~Tests almost pass, but there's a couple of failures for `tan`; this is the first:~~
https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/e6375b0bedd097e4efdc590b2ebdc52b9714811f/test/ITF1788_tests/libi …

Introduce `closure` function, extracted out of `convert`

---

src/intervals/trigonometric.jl

Current master:
```jl
julia> x = 3..4
[3, 4]
julia> @btime sin($x)
648.567 ns (14 allocations: 448 bytes)
[-0.756803, 0.141121]
```
This PR:
```jl
julia> @btime sin($x)
94.037 ns (0 allocations: 0 bytes)
[-0.756803, 0.141121]
```

Speed up sin and cos by a factor 6.5

---

src/display.jl

Fixes #93.
(Printing an interval with Julia 0.7 no longer segfaults!)

Fix ccall for interval display on 0.7

---

src/intervals/arithmetic.jl
src/intervals/rounding.jl

Fix to #120, including discussion found here: https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/122#pullrequestreview-111472074

Add specialized arithmetic methods for Interval{T} and T

---

REQUIRE
src/intervals/conversion.jl
src/intervals/rounding.jl
test/interval_tests/construction.jl

Use BigFloat parsing for Float64 to fix Windows bug.

---

src/intervals/set_operations.jl
src/multidim/setdiff.jl

Use Unicode `\setminus` so that the package is loadable on Julia 0.7-alpha.

Fix set minus in docs

---

src/IntervalArithmetic.jl
src/multidim/intervalbox.jl
test/multidim_tests/multidim.jl

Small changes that fix #136 and fix #110 . Moreover it appears during the elaboration of the PR that #30 is also fixed now.
I know that it is a bit awkward that the definition of `Region` is in the top file, but I couldn't see anywhere else to put it as it builds over both `interval/interval.jl` and `multidim/multidim.jl`.

Add Region and mid(X::IntervalBox, alpha)

---

src/multidim/intervalbox.jl
test/multidim_tests/multidim.jl

In current master `contains_zero( (-1..1)  )` or `isinf( (-1..1) × (-1..1) )` yields a stackoverflow error:
```julia
ERROR: StackOverflowError:
Stacktrace:
[1] isinf(::IntervalArithmetic.IntervalBox{2,Float64}) at /Users/benet/.julia/v0.6/IntervalArithmetic/src/multidim/intervalbox.jl:0
[2] isinf(::IntervalArithmetic.IntervalBox{2,Float64}) at /Users/benet/.julia/v0.6/IntervalArithmetic/src/multidim/intervalbox.jl:76 (repeats 79999 times)
```
This PR solves that, adding tests for that.

Broadcast in isinf and contains_zero, with tests

---

src/intervals/arithmetic.jl
test/interval_tests/bisect.jl
test/interval_tests/consistency.jl

- Allows to shift the middle point with `mid(-Inf..Inf, α)` with `α != 0.5` (`α` was previously ignored for infinite intervals).
- Change the expression which evaluate the midpoint to avoid that it returns `Inf` or `-Inf`.

Fix mid for large floats

---

src/display.jl

Fixes printing of intervals on master.
The non-public function `to_mpfr` that was previously used was removed in https://github.com/JuliaLang/julia/pull/29157.

Fix printing of intervals

---

src/intervals/trigonometric.jl
test/interval_tests/trig.jl

Use `rem2pi` to speed up quadrant calculation, giving overall 1.6x speedup roughly, and allowing calculations for large values of the argument.
TODO:
~- [ ] Use distance from pi/2 to decide which one is bigger?~

Faster trig functions

---

src/IntervalArithmetic.jl
src/intervals/complex.jl
src/intervals/set_operations.jl
src/multidim/intervalbox.jl
test/interval_tests/consistency.jl
test/multidim_tests/multidim.jl

Fixes #240.
Defines ` ∈` for `IntervalBox` correctly.
cc @Kolaru

Add "in" for IntervalBox

---

src/intervals/intervals.jl
src/multidim/intervalbox.jl
test/interval_tests/construction.jl
test/multidim_tests/multidim.jl

Construct an `IntervalBox` from opposite corners, even if those intervals are the wrong way round.
The function `force_interval` that creates an interval even when the endpoints are the wrong way round could be generally useful. It probably needs a better name.

Add IntervalBox constructor from vectors giving opposite corners

---

src/intervals/set_operations.jl
test/interval_tests/consistency.jl

Closes #256.
Some timings:
```julia
julia> using IntervalArithmetic
[ Info: Recompiling stale cache file /Users/forets/.julia/compiled/v1.1/IntervalArithmetic/Gjmwo.ji for IntervalArithmetic [d1acc4aa-44c8-5952-acd4-
ba5d80a2a253]
julia> Ik = [Interval(rand()-1,rand()) for _ in 1:4];
julia> using BenchmarkTools
julia> @btime intersect($Ik[1], $Ik[2], $Ik[3], $Ik[4])
17.967 ns (0 allocations: 0 bytes)
[-0.00897583, 0.433356]
julia> @btime reduce(intersect, $Ik)
29.546 ns (0 allocations: 0 bytes)
[-0.00897583, 0.433356]
julia> @btime intersect($Ik...)
121.255 ns (5 allocations: 160 bytes)
[-0.00897583, 0.433356]
```

Add n-ary intersection

---

src/intervals/arithmetic.jl
src/intervals/rounding_macros.jl
test/interval_tests/consistency.jl

Some functions were not type stable for `Interval{Float32}`. 
~This needs tests.~ Done

Type stability for some functions

---

Project.toml
REQUIRE

Specifically, `LinearAlgebra` and `Markdown` were missing. Note that the version of the package was also missing so I fixed it to 0.15.2 (the current one), until we want a new patch/minor release.

Add missing dependencies to Project.toml and remove REQUIRE

---

src/multidim/intervalbox.jl
test/multidim_tests/multidim.jl

Ref https://github.com/JuliaIntervals/IntervalOptimisation.jl/pull/45/files#r355474198. As far as I can tell, they are unnecessary. They disallow comparing IntervalBoxes of different numeric types, but it just dispatches to the 1D versions which can handle different types, e.g.
```julia
julia> x1 = -1.0..2.0
[-1, 2]
julia> x2 = big(1.0)..big(3.0)
[1, 3]₂₅₆
julia> x1 ∩ x2
[1, 2]₂₅₆
julia> x1 ∪ x2
[-1, 3]₂₅₆
julia> x1 ⊂ x2
false
julia> x1 ⊆ x2
false
julia> x1 ⊃ x2
false
julia> x1 ⊆ x2
false
```

Remove extra type constraints

---

src/IntervalArithmetic.jl
src/intervals/arithmetic.jl

implements JuliaIntervals/IntervalArithmetic.jl/issues/314

assign ≼ to precedes()

---

src/intervals/functions.jl
test/interval_tests/numeric.jl

On v0.16.2 I get
```julia
julia> pow(-2 .. -1, -1 .. -1)
∅
```
With this I get
```julia
julia> pow(-2 .. -1, -1 .. -1)
[-1, -0.5]
```

Return a concrete interval with negative-integer powers

---

src/intervals/set_operations.jl

Reverse the order of operations to avoid doing effectively the same check twice.

Speed up intersect

---

src/intervals/conversion.jl
test/interval_tests/numeric.jl

Fixes: https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/428

Support Rational - Int operations

---

src/display.jl
test/display_tests/display.jl

Fixes: https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/402
Followed @dpsanders's comment [here](https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/402#issuecomment-665360533).
Note: It prevented the error on my machine!
I am new to Julia. Please let me know if I am wrong with the format or something or even if I am completely wrong.

Overload Base.show for complex type

---

Project.toml
src/display.jl
test/display_tests/display.jl

Here is a summary of the changes
- complex intervals (fixes #287, fixes #332 ), `Base.show` was already implemented, I just modified it to be nicer with midpoint-format
```
julia> (1..2)+(3..4)im
(1.5 ± 0.5) + (3.5 ± 0.5)im
```
- cubic interval boxes (fixes #339) now cubic interval boxes are displayed in a more compact way with a superscript
```
julia> IntervalBox(1..2, 100)
[1, 2]¹⁰⁰
```
- thanks to the previous fix, now also empty interval boxes in the form `IntervalBox(emptyinterval(), N)` are displayed more compactly. (fixes #432 )
```
julia> IntervalBox(emptyinterval(), 100)
∅¹⁰⁰
```
However, Interval boxes where only some components are emptyintervals are still displayed normally, not sure whether this is a good idea
```
julia> IntervalBox(1..2, emptyinterval(), 3..4)
[1, 2] × ∅ × …
```

fixing displaying issues

---

Project.toml
src/IntervalArithmetic.jl
src/multidim/setdiff.jl
test/multidim_tests/multidim.jl

For start this new version is faster and allocates less. In the following benchmark, setdiff2 is the original one and setdiff the new one. In this commit I kept setdiff2 so that people can compare the two methods locally if they wish. I'll remove it once this is ready.
```jl
julia> X = IntervalBox(0..2, 3..4, 5..6)
[0, 2] × [3, 4] × [5, 6]
julia> Y = IntervalBox(0.5..0.6, 3.5..3.6, 5.5..5.6)
[0.5, 0.600001] × [3.5, 3.60001] × [5.5, 5.60001]
julia> @btime setdiff($X, $Y)
234.033 ns (11 allocations: 1.00 KiB)
6-element Vector{IntervalBox{3, Float64}}:
[0, 0.5] × [3, 4] × [5, 6]
[0.6, 2] × [3, 4] × [5, 6]
[0.5, 0.600001] × [3, 3.5] × [5, 6]
[0.5, 0.600001] × [3.6, 4] × [5, 6]
[0.5, 0.600001] × [3.5, 3.60001] × [5, 5.5]
[0.5, 0.600001] × [3.5, 3.60001] × [5.6, 6]
julia> @btime setdiff2($X, …
```

Speed up set difference of interval boxes

---

src/intervals/intervals.jl
test/interval_tests/construction.jl

`a..b` didn't check that `a ≤ b` when `b` is irrational. This PR fixes it.
before:
```
julia> π..1
[3.14159, 1]
julia> π..ℯ
[3.14159, 2.71829]
```
after:
```
julia> π..1
ERROR: ArgumentError: `[3.141592653589793, 1.0]` is not a valid interval. Need `a ≤ b` to construct `interval(a, b)`.
Stacktrace:
[1] interval
@ ~\.julia\packages\IntervalArithmetic\zFxqb\src\intervals\intervals.jl:111 [inlined]
[2] ..(a::Irrational{:π}, b::Int64)
@ IntervalArithmetic ~\.julia\dev\IntervalArithmetic\src\intervals\intervals.jl:154
[3] top-level scope
@ REPL[56]:1
julia> π..ℯ
ERROR: ArgumentError: `[π, ℯ]` is not a valid interval. Need `a ≤ b` to construct `interval(a, b)`.
Stacktrace:
[1] interval(a::Irrational{:π}, b::Irrational{:ℯ})
@ IntervalArithmetic …
```

fix `..` for irrational inputs

---

Project.toml
src/decorations/functions.jl
test/decoration_tests/decoration_tests.jl

`dist` for decorated intervals was accidentally defined as unary function [here](https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/master/src/decorations/functions.jl#L49-L55)
before:
```
julia> a = @decorated 1 2
[1, 2]_com
julia> b = @decorated 3 4
[3, 4]_com
julia> dist(a, b)
ERROR: MethodError: no method matching dist(::DecoratedInterval{Float64}, ::DecoratedInterval{Float64})
Stacktrace:
[1] top-level scope
@ REPL[13]:1
```
after:
```
julia> dist(a, b)
2.0
```

fix dist for decorated intervals

---

src/intervals/arithmetic.jl
src/multidim/intervalbox.jl
test/multidim_tests/multidim.jl

Improve mince and add method for non-uniform partition of IntervalBox

---

Project.toml
src/decorations/functions.jl
src/display.jl
src/intervals/arithmetic.jl
src/intervals/intervals.jl

See [this comment](https://github.com/JuliaIntervals/ITF1788.jl/issues/4#issuecomment-992043408) for the motivation.

Fix display of -0.0 to 0.0

---

Project.toml

- The older versions of CRlibm untars the deps which can't be supported on machines where you don't have root access
- CRlibm fails to build with
```
tar: crlibm-1.0beta4/trigo_fast.c: Cannot change ownership to uid 1000, gid 1000: Invalid argument
tar: crlibm-1.0beta4/trigpi.h: Cannot change ownership to uid 1000, gid 1000: Invalid argument
tar: crlibm-1.0beta4/ChangeLog: Cannot change ownership to uid 1000, gid 1000: Invalid argument
tar: crlibm-1.0beta4/triple-double.h: Cannot change ownership to uid 1000, gid 1000: Invalid argument
tar: crlibm-1.0beta4/log2-td.c: Cannot change ownership to uid 1000, gid 1000: Invalid argument
tar: crlibm-1.0beta4/exp-td-standalone.c: Cannot change ownership to uid 1000, gid 1000: Invalid argument
:
:
```

Bump CRlibm to 1 while keeping the existing compats

---

Project.toml
src/intervals/arithmetic.jl
test/interval_tests/consistency.jl

add mid radius inf sup diam for reals

---

src/intervals/functions.jl
test/interval_tests/numeric.jl

Currently this fails:
```julia
Interval(1.0f0) ^ Interval(1.0f0)
```
while this works
```julia
Interval(1.0) ^ Interval(1.0)
```
With this change both things will work, but I'm not too sure if it's the right thing to do. 
Happy to add tests etc.

Dispatch for exponentiation on Float32 intervals

---

src/intervals/arithmetic/power.jl

The idea behind this PR is to get the same results for `a^(1//n)` and `nthroot(a, n)` for `n::Integer`, when the comparison makes sense (there are small differences, which are related to `a`). This allows to pass a bunch of tests in `IntervalContractors.jl`, after some tweeks (see https://github.com/JuliaIntervals/IntervalContractors.jl/pull/55).

nthroot and rational power

---

Project.toml
src/IntervalArithmetic.jl
src/multidim/intervalbox.jl

This fixes an "unused type parameter" warning, removes a branch that cannot be reached because the Project.toml requires v1.5+ anyway, and removes the precompile line at the very beginning.

Fix type parameter warning, mild cleanup

---

src/IntervalArithmetic.jl
src/intervals/conversion.jl
src/intervals/intervals.jl

I was looking at usage of Irrational in packages (https://juliahub.com/ui/Search?q=Irrational&type=symbols&u=use&t=type), to estimate how breaking https://github.com/JuliaMath/IrrationalConstants.jl/pull/19 (motivated by https://github.com/JuliaLang/julia/issues/46531) will be. IntervalArithmetic showed up in the list of packages that define methods for `Irrational` but it seems the definitions could be generalized to support `AbstractIrrational`.

Use `AbstractIrrational` instead of `Irrational`

---

src/intervals/real_interface.jl
test/interval_tests/construction.jl

Julia already defines the fallback method `real(x::Real) = x` so there is no need to add a new method.
Also, minor format changes in the docstrings and the header of the file.

1.0-dev: remove superfluous `Real`-like methods for `Interval`

---

src/intervals/construction.jl
src/intervals/real_interface.jl
test/interval_tests/construction.jl

Before this PR
```Julia
julia> Interval(Interval(1))
ERROR: MethodError: Interval(::Interval{Float64}) is ambiguous.
Candidates:
(::Type{T})(x::T) where T<:Number
@ Core boot.jl:792
Interval(a)
@ IntervalArithmetic ~/.julia/dev/dev_IA/IntervalArithmetic/src/intervals/construction.jl:73
Possible fix, define
Interval(::Interval)
Stacktrace:
[1] top-level scope
@ REPL[3]:1
```
With this PR:
```Julia
julia> Interval(Interval(1))
[1, 1]
```
The PR also contains some minor changes:
- simplified the logic in `_normalisezero` as I did not observe any impact on performance. But perhaps I am missing something?
- only keep the required inner constructor (the other one is now a regular outer constructor)

1.0-dev: fix `Interval(::Interval)` ambiguity error

---

src/intervals/arithmetic/basic.jl
src/intervals/construction.jl
test/interval_tests/construction.jl
test/interval_tests/numeric.jl

- Fix ambiguities with `+`, `-`, `*` and `/` when the operands are `Interval`s with different `numtype`. The mechanism relies on `promote`, so `promote_rule` is defined, as a side-effect `[Interval{Float32}(pi), Interval{Float64}(pi)]::Vector{Interval{Float64}}` with guaranteed error bounds.
- Fix typos in dosctrings
Before this PR:
```julia
julia> Interval{Float64}(1) + Interval{Float32}(1)
ERROR: MethodError: +(::Interval{Float64}, ::Interval{Float32}) is ambiguous.
Candidates:
+(b::Real, a::Interval)
@ IntervalArithmetic ~/.julia/dev/dev_IA/IntervalArithmetic/src/intervals/arithmetic/basic.jl:31
+(a::Interval{T}, b::S) where {T, S<:Real}
@ IntervalArithmetic ~/.julia/dev/dev_IA/IntervalArithmetic/src/intervals/arithmetic/basic.jl:30
Possible fix, define
+(::Interval{T}, ::S) where {T, …
```

1.0-dev: fix `interval(::Interval)` and some ambiguities

---

src/IntervalArithmetic.jl
src/display.jl
test/display_tests/display.jl

Over the week-end I experimented with the printing mechanism of the 1.0-dev branch. This is the resulting PR 🙂.
Fix #316, #434.
It seems that the alignment issue when printing arrays is linked to the fact that `Interval <: Real` and sometimes the bounds of the intervals are printed with no decimal points. The current behaviour (before this PR) relies on the format `"%.g"` which gives the shortest form for a given number (e.g. `1.0` would be returned as `1`).
So this would explain also why `IntervalBox` had no printing issues: it is not a subtype of `Real`.
In this PR I tried to stay as close as possible to the current behaviour, so the only **visual change** is that exact integers are displayed with a trailing decimal point and 0, for instance `1` is printed as `1.0`.
I have modified the …

1.0-dev: improve printing and fix alignment issue

---

src/intervals/arithmetic/trigonometric.jl
src/intervals/rounding.jl
test/interval_tests/trigonometric.jl

This PR is essentially a revival of the PR #421 which got forgotten unfortunately.
Closes #381; closes #412.
This PR also refactors the code in trigonometric.jl; the code is about 200 lines shorter.

Improve accuracy of `sinpi` and `cospi`

---

NEWS.md
Project.toml
ext/IntervalArithmeticRecipesBaseExt.jl
test/runtests.jl

Closes #605.
In the future we should add recipes like this for Makie.jl.

Add RecipesBase as an extension

---

ext/IntervalArithmeticRecipesBaseExt.jl

When plotting an interval box with `Plots.jl` and the `GR` backend, the produced rectangle has borders on all four sides. However, when using other backends like `UnicodePlots`, `PGFPlotsX` or `PythonPlots`, the left border is missing (left side in the image below). This patch resolves the issue (right side):

Properly closed interval boxes for other backends than GR

---

src/intervals/construction.jl
test/interval_tests/complex.jl

When constructing an interval from one real and one complex argument I expected it to treat the imaginary part of the real argument as zero. What happens is instead that it takes the imaginary part of the interval to only depend on the complex argument, e.g.
```julia
julia> interval(0, complex(1, 1))
[0.0, 1.0]_com + ([1.0, 1.0]_com)im
```
Compare this to what we get if we make the first argument complex
```julia
julia> interval(complex(0), complex(1, 1))
[0.0, 1.0]_com + ([0.0, 1.0]_com)im
```
This behavior could of course be by design, but since there are no tests for it I would guess that it is just a mistake. Since we have `isequal(0, complex(0))` it seems natural that they would both give the same result.
This PR changes it so that the real argument is treated as a complex argument …

Construction of interval when mixing real and complex arguments

---

src/intervals/interval_operations/bisect.jl
src/intervals/interval_operations/numeric.jl
test/interval_tests/consistency.jl

I am looking into updating IntervalRootFinding.jl for v0.22.
One think that disappeared that we need is `scaled_mid`.
This PR reintroduces it by giving `mid` an optional argument.
Technically it makes the default `mid` a bit slower (4 flops and 1 division, instead of 2 flops). I can split the default if it is somehow very critical for someone.
The new formula looks weird, but that's what we need to pass the test suite.

(re)Introduce scaling factor for mid

---

src/intervals/construction.jl
src/intervals/flavor.jl
src/intervals/intervals.jl
test/interval_tests/construction.jl

Ensure correct rounding for irrationals

---

Project.toml
src/IntervalArithmetic.jl
src/intervals/arithmetic/basic.jl
src/intervals/arithmetic/hyperbolic.jl
src/intervals/arithmetic/power.jl
src/intervals/arithmetic/trigonometric.jl
src/intervals/interval_operations/numeric.jl
src/intervals/rounding.jl
test/interval_tests/complex.jl
test/interval_tests/trigonometric.jl

This PR fixes the rounding mechanism to be thread-safe. It removes CRlibm.jl as a dependency, and directly calls methods from CRlibm_jll, or from MPFR as suggested by @Joel-Dahne.
This PR also fixes rounding for intervals with rational bounds by returning a float interval for non exact operations.
To do: we should probably also fix our quadrant method for trigonometric functions which is not thread-safe due to https://github.com/JuliaLang/julia/issues/52862

Fix thread-safe in rounding

---

src/intervals/arithmetic/trigonometric.jl

Closes #620
This PR makes sure we no longer rely on Julia default code to compare with `π` due to https://github.com/JuliaLang/julia/issues/52862.
This should ensure that trigonometric functions are thread-safe.
The PR also reworks the inner function `_quadrant`.
Now I consistently get the same precision before and after calling `sin` on multiple threads (see also #612):
```Julia
julia> x = interval(BigFloat, 1)
[1.0, 1.0]₂₅₆_com
julia> y = sin(x)
[0.84147, 0.841472]₂₅₆_com
julia> Threads.@threads for _ in 1:1000
z = sin(x)
@assert isequal_interval(y, z)
end
julia> precision(BigFloat)
256
```
The implementation is based on @Joel-Dahne, @lbenet and @dpsanders suggestions.
Hopefully everything is in order! 🙂

Ensure thread-safety for trigonometric functions

---

src/intervals/arithmetic/power.jl
test/interval_tests/power.jl

Avoid `convert` in `^` for literal powers

---

Project.toml
ext/IntervalArithmeticForwardDiffExt.jl
test/interval_tests/forwarddiff.jl
test/runtests.jl

This PR overlead ForwardDiff default behavior, so that it works with intervals.
It is necessary for updating IntervalRootFinding.jl because many tests there rely on polynomials.

ForwardDiff extension for power

---

src/intervals/real_interface.jl
test/interval_tests/consistency.jl

Allow `==` if one of the operand is a thin interval

---

docs/src/manual/construction.md

This PR adds documentation for the 'NG' decoration.  See issue #634 .

Description NG decoration

---

src/display.jl
src/intervals/arithmetic/hyperbolic.jl
src/intervals/arithmetic/power.jl
src/intervals/arithmetic/trigonometric.jl
src/intervals/interval_operations/numeric.jl
test/interval_tests/consistency.jl
test/interval_tests/power.jl
test/interval_tests/trigonometric.jl

The goal of this PR is to address https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/41 and and https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/295.
TODO: `sqrt`, `^`, and inverse trigonometric/hyperbolic functions.

Improve support for complex intervals

---

ext/IntervalArithmeticForwardDiffExt.jl
src/intervals/exact_literals.jl

This contains two small fixes that are useful for the update of IntervalRootFinding. 
1. Allow to use `ExactReal{<:Integer}` to index an array.
2. Fix derivative of `^` when mixing `ExactReal` and `Interval` in the ForwardDiff extension.
The first one in particular may be handy for everyone, when working with vectors of interval for example. With this PR, indexing work as intuitively expected with `@exact`
```julia
julia> @exact f(x) = x[1] + x[2] + 1.2
f (generic function with 1 method)
julia> X = [interval(-1, 1), interval(-0.1, 3)]
2-element Vector{Interval{Float64}}:
[-1.0, 1.0]_com
[-0.100001, 3.0]_com
julia> f(X)
[0.0999999, 5.20001]_com
```

Small fixes for ExactReal

---

src/display.jl

This PR simply adds the boolean keyword `ng_flag` to the `setdisplay` function. When set to false, the flag "NG" is not displayed.
Before merging this PR, can anyone think of a better keyword name than `ng_flag`?
Closes #639

Add an option to not display the NG flag

---

src/intervals/exact_literals.jl
test/interval_tests/exact_literals.jl

This PR allows `@exact` to work with `BareInterval`, eg
```Julia
julia> @exact bareinterval(3, 4) ^ 2
BareInterval{Float64}(9.0, 16.0)
```
I think this PR also addresses the concerns raised in #646.
Closes #646.

Extend `ExactReal` to work with `BareInterval`

---

src/intervals/interval_operations/set_operations.jl

Redo of https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/379, which seems to have got lost.
3–4x faster on my machine.

Fast intersection for BareInterval

---

src/symbols.jl

These were added to `IntervalArithmetic.Symbols` but weren't exported.

Export \sqcap and \sqcup

---

src/intervals/arithmetic/trigonometric.jl

This PR implements a reliable code to determine quadrants for trigonometric functions.
@dpsanders do you mind having a look?
Closes #622

Reliable quadrant

---

Project.toml
ext/IntervalArithmeticForwardDiffExt.jl
src/intervals/exact_literals.jl
test/interval_tests/forwarddiff.jl

The fixes the support for derivatives of powers containing ExactReal.
This *should* be the last missing piece before IntervalRootFinding can be upgraded to IA v0.22.

Fix ExactReal with power in ForwardDiff

---

src/intervals/exact_literals.jl
test/interval_tests/exact_literals.jl

This was preventing
```
ExactReal{Int64}(3)
```
which should be allowed.

Remove inner constructor for ExactReal

---

src/intervals/interval_operations/numeric.jl
src/intervals/interval_operations/set_operations.jl

This PR explicitly returns an NaI by calling `nai` whenever one of the argument is an NaI.
As pointed out in #662, before this PR we would obtain for `hull` a non trivial interval with `ill` decoration which could lead to errors down the line if one accesses the bounds of the interval through `getproperty`.
Closes #662
Also, this PR should supersede #663.

Return explicitly an NaI for `intersect_interval` and `hull`

---

docs/src/manual/usage.md

This PR details the changes on boolean and set functions. Alternatives to commonly used Base functions are provided.
Closes #524.

Add documentation about boolean/set functions

---

src/intervals/exact_literals.jl

Defines `Base.hash` and `Base.isfinite` for `ExactReal`s.
This is necessary so that they work with Symbolics.jl.

Base utilities for exact reals

---

src/intervals/arithmetic/trigonometric.jl
test/interval_tests/trigonometric.jl

When finding the quadrant of `x::AbstratctFloat` which is not inside $(-\pi, \pi)$, we divide by $2\pi$. The resulting interval may cover two quadrants due to rounding and we choose the one so that we cover the largest interval.
This PR ensures that we keep track of this widening.
Closes #683

Fix quadrant

---

ext/IntervalArithmeticForwardDiffExt.jl
src/intervals/construction.jl
src/intervals/exact_literals.jl
test/interval_tests/construction.jl
test/interval_tests/forwarddiff.jl

This PR re-introduce `Interval(::Real)` and `Interval{T}(::Real)`, marking the output with the "NG flag".
It also adds a conversion in the ForwardDiff extension between `ExactReal` and `Dual`.
Closes #685

Extend conversion

---

src/intervals/exact_literals.jl

Prevent name ambiguity warning during precompilation on nightly Julia.
See:
* https://github.com/JuliaLang/julia/issues/25744
* https://github.com/JuliaLang/julia/issues/57290
* https://github.com/JuliaLang/julia/pull/57311

explicitly qualify `Bool` while adding method

---

ext/IntervalArithmeticDiffRulesExt.jl
ext/IntervalArithmeticForwardDiffExt.jl
test/interval_tests/forwarddiff.jl

As pointed out by @dpsanders, it is much more consistent to return $[-1, 1]$ for the derivative of `abs`. It also resolves a broken test for second-order derivatives with [ForwardDiff.jl](https://github.com/JuliaDiff/ForwardDiff.jl).

Return [-1,1] for the derivative of `abs` at 0

---

ext/IntervalArithmeticRandomExt.jl
src/intervals/interval_operations/numeric.jl
test/interval_tests/consistency.jl

This properly addresses #709. Closes #709.
This also contains a fix for a bug with `mid(x, t)` and $t \ne 1/2$, where floating point errors could result in a midpoint value outside the prescribed interval.
cc @lbenet @dpsanders

Add `rand(::Interval)`

---

test/interval_tests/display.jl

This PR add a version check in the tests so that we follow the change of display of BigFloat exponent.
Solve the failing test in nightly.

Fix display test for BigFloat newest julia versions

---

Project.toml
docs/Project.toml
docs/make.jl
docs/src/manual/interfaces/Arblib.md
ext/IntervalArithmeticArblibExt.jl
test/Project.toml
test/interval_tests/IntervalArithmeticArblibExt.jl
test/runtests.jl

As discussed in #721, it would be nice to make the Arblib.jl and IntervalArithmetic.jl packages talk to each other. This is an attempt at making basic conversion between `Interval` and `Arb` work.
```julia
julia> using Arblib, IntervalArithmetic
julia> x = interval(BigFloat, π)
[3.14159, 3.1416]₂₅₆_com
julia> y = Arb(x)
[3.1415926535897932384626433832795028841971693993751058209749445923078164062862 +/- 5.38e-77]
julia> cos(x)
[-1.0, -0.999999]₂₅₆_com
julia> cos(y)
[-1.000000000000000000000000000000000000000000000000000000000000000000000000000 +/- 1.78e-77]
```
It is also possible to construct matrices and do basic linear algebra
```julia
julia> A = interval.(rand(BigFloat, 2, 2))
2×2 Matrix{Interval{BigFloat}}:
[0.15383, 0.153831]₂₅₆_com  [0.655025, 0.655026]₂₅₆_com
[0.165259, …
```

Add extension for Arblib.jl

---

.github/workflows/CI.yml
Project.toml
ext/IntervalArithmeticLinearAlgebraExt.jl
src/IntervalArithmetic.jl
src/display.jl
src/intervals/arithmetic/basic.jl
src/intervals/arithmetic/power.jl
src/intervals/arithmetic/trigonometric.jl
src/intervals/construction.jl
src/intervals/exact_literals.jl
src/intervals/flavor.jl
src/intervals/interval_operations/cancellative.jl
src/intervals/interval_operations/constants.jl
src/intervals/interval_operations/numeric.jl
src/intervals/interval_operations/set_operations.jl
src/intervals/intervals.jl
src/intervals/parsing.jl
src/intervals/rounding.jl
test/interval_tests/IntervalArithmeticArblibExt.jl
test/interval_tests/display.jl
test/interval_tests/exact_literals.jl

Release 1.0
