JuliaIntervals/IntervalArithmetic.jl

docs/src/multidim.md

likely from awhile back, probably not necessary.

Found another version reference

---

examples/draw_function_image.jl
examples/standard_map.jl
src/intervals/rounding.jl
src/intervals/set_operations.jl
src/intervals/special.jl
src/intervals/trigonometric.jl
src/multidim/intervalbox.jl
src/plot_recipes/plot_recipes.jl

This is what I got when running FemtoCleaner locally @dpsanders

fix deprecations [femtocleaner]

---

docs/make.jl
docs/src/index.md
docs/src/intro.md

https://discourse.julialang.org/t/ann-intervalrootfinding-jl-for-finding-all-roots-of-a-multivariate-function/9515/29
@dpsanders I have made minor changes to the original content. How do I test the changes made to the docs?

Add intro to interval arithmetic in docs

---

src/multidim/intervalbox.jl

This gives significant speedups for several of the functions.

Use broadcasting consistently for multidim operations

---

src/intervals/arithmetic.jl
test/interval_tests/numeric.jl

This was reverted in #132.
Putting it back in.

Redo #131, fix a - x

---

src/display.jl

Fix #135
I created a separate branch for the fix. Sorry for my lack of git skills.

Fix subscriptify

---

src/intervals/conversion.jl
src/intervals/intervals.jl
test/interval_tests/construction.jl

Add methods to use .. notation with Irrationals

---

src/intervals/functions.jl

Fixes #164.
i.e. error in literal powers like `X^-2`.

Fix literal powers

---

src/intervals/rounding.jl
test/interval_tests/numeric.jl

Use fast path for sqrt and inv

---

src/multidim/arithmetic.jl
src/multidim/intervalbox.jl
test/multidim_tests/multidim.jl

Add missing set operations involving `IntervalBox`es, with tests

---

src/intervals/arithmetic.jl
test/interval_tests/numeric.jl

Fix bug in extended_div function

---

src/IntervalArithmetic.jl
src/intervals/intervals.jl
src/intervals/precision.jl
src/intervals/trigonometric.jl
test/display_tests/display.jl
test/interval_tests/complex.jl
test/interval_tests/construction.jl
test/interval_tests/trig.jl

This superseeds PR #337 by implementing a new constructor for irrational, in such a way no overhead are produced.

Better constructors for irrationals

---

src/intervals/functions.jl
test/interval_tests/numeric.jl

Extend domain of log1p

---

docs/src/intro.md

removed a comma, added a period.

Fix punctuation

---

src/IntervalArithmetic.jl
src/intervals/arithmetic.jl
src/intervals/set_operations.jl
src/multidim/intervalbox.jl
test/interval_tests/numeric.jl
test/multidim_tests/multidim.jl

Add `mince` for intervals and interval boxes

---

src/IntervalArithmetic.jl
test/runtests.jl

Remove old version checks

---

.travis.yml
Project.toml
appveyor.yml
src/intervals/arithmetic.jl

Fixes the performance regression in #380.

Force inlining and specialisation for multiplication

---

.travis.yml
Project.toml
appveyor.yml
src/IntervalArithmetic.jl

Import isadjoint when necessary

---

src/display.jl
test/display_tests/display.jl

Display Interval{Float32} with f0

---

Project.toml
src/intervals/arithmetic.jl
test/interval_tests/consistency.jl

Fix cancelminus

---

Project.toml

Version bump for Polynomials.

---

src/intervals/arithmetic/basic.jl
test/interval_tests/numeric.jl

```julia
julia> 0.0 * interval(1)
[1.0, 1.0]  # master
[0.0, 0.0]  # after fix
```

Fix multiplication with zero

---

src/intervals/interval_operations/bisect.jl
src/intervals/interval_operations/set_operations.jl

Add in-place set operations

---

src/intervals/interval_operations/boolean.jl
src/intervals/intervals.jl
src/intervals/real_interface.jl
test/interval_tests/consistency.jl

Fix `one` and define `isthinone`

---

src/intervals/arithmetic/trigonometric.jl
test/interval_tests/trigonometric.jl

Add `sind`/`cosd`/`sincosd`

---

src/intervals/construction.jl
test/interval_tests/consistency.jl

Allow changing decoration

---

src/display.jl

Ensure `string` is consistent with `show`

---

src/intervals/interval_operations/boolean.jl
test/interval_tests/consistency.jl

Fix `isdisjoint_interval` for multiple input

---

src/IntervalArithmetic.jl

This PR aims to address #708.
@jaakkor2 can you check if there are less invalidation with this PR?

Remove specialised `similar` methods

---

src/intervals/flavor.jl
test/interval_tests/construction.jl

Prevent issue with modular arithmetic
